# Generated by Django 4.1.7 on 2023-03-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HotelMadonie", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotelmadonie",
            old_name="cognome",
            new_name="titolo",
        ),
        migrations.RemoveField(
            model_name="hotelmadonie",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="hotelmadonie",
            name="prezzo",
        ),
        migrations.AddField(
            model_name="hotelmadonie",
            name="immagine",
            field=models.ImageField(default=0, upload_to="images/"),
            preserve_default=False,
        ),
    ]
