# Generated by Django 4.1.7 on 2023-03-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HotelMadonie", "0002_rename_cognome_hotelmadonie_titolo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelmadonie",
            name="immagine",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
