# Generated by Django 4.1.7 on 2023-03-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HotelMadonie", "0004_alter_hotelmadonie_immagine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelmadonie",
            name="immagine",
            field=models.ImageField(upload_to=""),
        ),
    ]
