# Generated by Django 4.1.7 on 2023-03-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HotelMadonie", "0005_alter_hotelmadonie_immagine"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prenotazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("cognome", models.CharField(max_length=50)),
                ("data_arrivo", models.DateField()),
                ("data_partenza", models.DateField()),
                ("num_camere", models.IntegerField()),
                ("num_ospiti", models.IntegerField()),
                ("prezzo_totale", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name="hotelmadonie",
            name="titolo",
            field=models.TextField(max_length=20),
        ),
    ]
