# Generated by Django 4.1.7 on 2023-03-24 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HotelMadonie", "0007_prenotazione_ora_arrivo_prenotazione_tipo_camera"),
    ]

    operations = [
        migrations.CreateModel(
            name="nuova_prenotazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("cognome", models.CharField(max_length=50)),
                ("data_arrivo", models.DateField()),
                ("data_partenza", models.DateField()),
                ("ora_arrivo", models.TimeField(default=datetime.datetime.now)),
                ("num_camere", models.IntegerField()),
                ("num_ospiti", models.IntegerField()),
                ("prezzo_totale", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "tipo_camera",
                    models.CharField(
                        choices=[
                            ("singola", "Singola"),
                            ("doppia", "Doppia"),
                            ("tripla", "Tripla"),
                        ],
                        default="Singola",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
