# Generated by Django 4.1.7 on 2023-03-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HotelMadonie", "0009_delete_nuova_prenotazione_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prenotazione",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="prenotazione",
            name="tipo_camera",
            field=models.CharField(
                choices=[
                    ("Singola", "Singola"),
                    ("Doppia", "Doppia"),
                    ("Tripla", "Tripla"),
                ],
                max_length=100,
            ),
        ),
    ]
