# Generated by Django 4.1.7 on 2023-03-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HotelMadonie", "0011_prenotazione_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prenotazione",
            name="numero",
            field=models.CharField(max_length=15),
        ),
    ]
